### ISSUE TITLE
Switch to csv

### ISSUE THREAD

**Issue by friep** [friep/correlaid-utils#8]
JSON format causes way too many problems, change to csv to store the data (it's rectangular anyway).

**Comment by MKyhos** [comment]
A feature the community desired for long! :blush:  Thanks a lot! :pray:

**Comment by friep** [comment]
thanks for the encouragement @MKyhos !! it should be fixed now. 🙏

**Comment by MKyhos** [comment]
Awesome! Thanks so much! 
![Alt Text](https://media.giphy.com/media/3KC2jD2QcBOSc/giphy.gif)

**Comment by friep** [comment]
https://media.giphy.com/media/3fi9LYHrwzbqOQcWnF/giphy.gif

**Comment by friep** [comment]
![](https://media.giphy.com/media/GR5cUyPElce63sDd7z/giphy.gif)

**Comment by friep** [comment]
![find-the-difference](https://user-images.githubusercontent.com/13187448/100869986-2d096680-349e-11eb-8d36-57d4f7be4227.png)

@MKyhos
